-- SECURITY FIX: the original daily_codes policy let any anon/authenticated
-- client directly increment `uses` from the browser, which meant a user
-- could bypass the usage cap entirely by calling Supabase themselves.
-- All redemption now happens server-side (service role) through the
-- redeem_daily_code() function below, so this policy is no longer needed
-- — and must be removed for the cap to mean anything.
drop policy if exists "update_daily_codes" on daily_codes;

-- Daily codes are now generated by the admin panel, not hardcoded.
-- Bump the default cap to the new hard limit of 500 redemptions/day.
alter table daily_codes alter column max_uses set default 500;

-- Tracks which user redeemed which daily code, so each user can redeem a
-- given day's code only once (enforced by the unique constraint, not just
-- app logic — a user calling the API twice in parallel can't double-spend).
create table if not exists code_usages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  code text not null,
  used_at timestamptz not null default now(),
  used_date date not null default current_date,
  unique (user_id, code)
);

create index if not exists code_usages_user_date_idx on code_usages(user_id, used_date);

alter table code_usages enable row level security;

-- Users can see their own redemption history (e.g. to know they've already
-- unlocked manual entry today) but can never write to this table directly —
-- only redeem_daily_code() (run via the service role from our API) can.
create policy "read_own_code_usages" on code_usages
  for select to authenticated
  using (auth.uid() = user_id);

-- Atomically validates and redeems a daily code in one step: checks the
-- code is valid for today, hasn't hit its 500-use cap, and this user
-- hasn't already used it — then records the usage and bumps the counter.
-- The row lock (`for update`) prevents two simultaneous requests from both
-- reading "499/500" and both succeeding, which a check-then-write done as
-- two separate client calls could not safely prevent.
create or replace function redeem_daily_code(p_user_id uuid, p_code text)
returns table(success boolean, message text) as $$
declare
  v_uses int;
  v_max_uses int;
  v_already_used boolean;
begin
  select uses, max_uses into v_uses, v_max_uses
  from daily_codes
  where code = p_code and valid_date = current_date
  for update;

  if v_uses is null then
    return query select false, 'invalid_or_expired';
    return;
  end if;

  if v_uses >= v_max_uses then
    return query select false, 'limit_reached';
    return;
  end if;

  select exists(
    select 1 from code_usages where user_id = p_user_id and code = p_code
  ) into v_already_used;

  if v_already_used then
    return query select false, 'already_used';
    return;
  end if;

  insert into code_usages (user_id, code) values (p_user_id, p_code);
  update daily_codes set uses = uses + 1 where code = p_code and valid_date = current_date;

  return query select true, 'ok';
end;
$$ language plpgsql;
